"""
EM-modelling routines. The implemented routines might not be the fastest
solution to your specific problem. Use these routines as template to create
your own, problem-specific modelling routine!

Principal routines:

- :func:`bipole`
- :func:`dipole`

The main routine is :func:`bipole`, which can model finite-length dipole
source(s) and dipole receiver(s) of arbitrary direction, for electric or
magnetic (field or flux) sources and receivers, both in frequency and in time.
A subset of :func:`bipole` is :func:`dipole`, which models infinitesimal small
dipoles along the principal axes x, y, and z.

Further routines are:

- :func:`analytical`: Calculate analytical fullspace and halfspace solutions.
- :func:`dipole_k`: Calculate the electromagnetic wavenumber-domain solution.
- :func:`gpr`: Calculate the Ground-Penetrating Radar (GPR) response.
- :func:`ip_and_q`: Calculate in-phase and quadrature responses.

The :func:`dipole_k` routine can be used if you are interested in the
wavenumber-domain result, without Hankel nor Fourier transform. It calls
straight the :mod:`empygrad.kernel`. The :func:`gpr`-routine convolves the
frequency-domain result with a wavelet, and applies a gain to the time-domain
result. This function is still experimental.

The modelling routines make use of the following two core routines:

- :func:`fem`: Calculate wavenumber-domain electromagnetic field and carry out
  the Hankel transform to the frequency domain.
- :func:`tem`: Carry out the Fourier transform to time domain after
  :func:`fem`.

"""
# Copyright 2016 The emsig community.
#
# This file is part of empygrad.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.
import copy

import numpy as np

from empygrad import kernel
from empygrad.utils import (
        check_time, check_time_only, check_model, check_frequency,
        check_hankel, check_loop, check_dipole, check_bipole, check_ab,
        check_solution, get_abs, get_geo_fact, get_azm_dip, get_off_ang,
        get_layer_nr, get_kwargs, printstartfinish, conv_warning, EMArray)
from empymod import transform

__all__ = ['bipole', 'dipole', 'analytical', 'gpr', 'dipole_k',
           'ip_and_q', 'fem', 'tem']


def __dir__():
    return __all__


def bipole(src, rec, depth, res, freqtime, signal=None, aniso=None,
           epermH=None, epermV=None, mpermH=None, mpermV=None, msrc=False,
           srcpts=1, mrec=False, recpts=1, strength=0, jac=None, **kwargs):
    r"""Return EM fields due to arbitrary rotated, finite length EM dipoles.

    Calculate the electromagnetic frequency- or time-domain field due to
    arbitrary rotated, finite electric or magnetic dipole sources, measured by
    arbitrary rotated, finite electric or magnetic dipole receivers. By
    default, the electromagnetic response is normalized to source and receiver
    of 1 m length, and source strength of 1 A.

    A magnetic dipole has a moment of :math:`I^m ds`. However, if the magnetic
    dipole is generated by an electric-wire loop, this changes to :math:`I^m =
    i\omega\mu A I^e`, where A is the area of the loop. The same factor
    :math:`i\omega\mu A`, applies to the receiver, if it consists of an
    electric-wire loop. This can be achieved by setting ``msrc`` or ``mrec`` to
    ``'b'``. The current implementation only handles loop sources and receivers
    in layers where :math:`\mu_r^h=\mu_r^v`; the horizontal magnetic
    permeability is used, and a warning is thrown if the vertical differs from
    the horizontal one.


    See Also
    --------
    :func:`dipole` : EM fields due to infinitesimal small EM dipoles.
    :func:`analytical` : Analytical full- and half-space solutions.


    Parameters
    ----------
    src, rec : list of floats or arrays
        Source and receiver coordinates (m):

        - [x0, x1, y0, y1, z0, z1] (dipole of finite length)
        - [x, y, z, azimuth, dip]  (dipole, infinitesimal small)

        Note that when the coordinates are defined as finite length dipoles, it
        will still return an infinitesimal small dipole at its center unless
        ``srctpts;recpts`` is set to a value of 3 or higher.

        For `N` sources or receivers, all variables must be of size `N` or 1
        (in the latter case it will be expanded to `N`).

        Angles (coordinate system is either left-handed with positive z down or
        right-handed with positive z up; East-North-Depth):

        - azimuth (°): horizontal deviation from x-axis, anti-clockwise.
        - +/-dip (°): vertical deviation from xy-plane down/up-wards.

        Sources or receivers placed on a layer interface are considered in the
        upper layer.

    depth : list
        Absolute layer interfaces z (m); #depth = #res - 1
        (excluding +/- infinity).

    res : array_like
        Horizontal resistivities rho_h (Ohm.m); #res = #depth + 1.

        Alternatively, res can be a dictionary. See the main manual of empygrad
        too see how to exploit this hook to re-calculate etaH, etaV, zetaH, and
        zetaV, which can be used to, for instance, use the Cole-Cole model for
        IP.

    freqtime : array_like
        Frequencies f (Hz) if ``signal==None``, else times t (s); (f, t > 0).

    signal : {None, -1, 0, 1, dict}, default: None
        Source signal:

        - None: Frequency-domain response
        - -1 : Switch-off time-domain response
        - 0 : Impulse time-domain response
        - +1 : Switch-on time-domain response
        - dict : Arbitrary waveform

          For an arbitrary waveform, the dictionary must contain the following
          keyword-value pairs:

          - nodes : array_like
              Nodes of the waveform.
          - amplitudes : array_like
              Amplitudes (current) of the waveform.
          - signal : {-1, 0, 1}, default: 0
              Signal that is convolved with the waveform.
          - nquad : int, default: 3
              Number of quadrature points for the waveform segments.

    aniso : array_like, default: ones
        Anisotropies lambda = sqrt(rho_v/rho_h) (-); #aniso = #res.

    epermH, epermV : array_like, default: ones
        Relative horizontal/vertical electric permittivities
        epsilon_h/epsilon_v (-); #epermH = #epermV = #res. If epermH is
        provided but not epermV, isotropic behaviour is assumed.

    mpermH, mpermV : array_like, default: ones
        Relative horizontal/vertical magnetic permeabilities mu_h/mu_v (-);
        #mpermH = #mpermV = #res. If mpermH is provided but not mpermV,
        isotropic behaviour is assumed.

    msrc, mrec : bool or string, default: False
        - ``True``: If True, source/receiver (msrc/mrec) is magnetic, else
          electric.
        - ``'b'``: Source and receiver can also be set to ``msrc='b'`` and
          ``mrec='b'``, which means that they correspond to loops, simulating
          magnetic flux density dB/dt instead of magnetic field H, with B=μH.
          It computes the same as ``mrec=True``, but multiplies it with iωμ of
          the layer of the receiver in the frequency domain (and accordingly
          four the source). Only implemented for isotropic magnetic
          permittivities at source/receiver level.
        - ``'j'``: The receiver can also be set to ``mrec='j'``, in which case
          the electric current density is returned (with the approximation that
          the current density is proportional to the electric field, J=σE).
          Only implemented for isotropic resistivities and electric
          permittivities at receiver level.

    srcpts, recpts : int, default: 1
        Number of integration points for dipole source/receiver:

        - srcpts/recpts < 3  : infinitesimal small dipole at the center.
        - srcpts/recpts >= 3 : finite length approximation with `N` points.

    strength : float, default: 0.0
        Source strength (A):

        - If 0, output is normalized to source and receiver of 1 m length (or 1
          m² area if 'b'), and source strength of 1 A.
        - If != 0, output is returned for given source and receiver length, and
          source strength.

        Note that the strength is simply a multiplication factor, and can be
        used for many other things therefore.

    verb : {0, 1, 2, 3, 4}, default: 2
        Level of verbosity:

        - 0: Print nothing.
        - 1: Print warnings.
        - 2: Print additional runtime and kernel calls
        - 3: Print additional start/stop, condensed parameter information.
        - 4: Print additional full parameter information

    ht : {'dlf', 'qwe', 'quad'}, default: 'dlf'
        Flag to choose either the *Digital Linear Filter* (DLF) method, the
        *Quadrature-With-Extrapolation* (QWE), or a simple *Quadrature* (QUAD)
        for the Hankel transform.

    htarg : dict, optional
        Possible parameters depends on the value for ``ht``:

        - If ``ht='dlf'``:

          - ``dlf``: string of filter name in :mod:`empygrad.filters` or the
            filter method itself. (default:
            ``empygrad.filters.Hankel().key_201_2009``)
          - ``pts_per_dec``: points per decade; (default: 0):

            - If 0: Standard DLF.
            - If < 0: Lagged Convolution DLF.
            - If > 0: Splined DLF

        - If ``ht='qwe'``:

          - ``rtol``: relative tolerance (default: 1e-12)
          - ``atol``: absolute tolerance (default: 1e-30)
          - ``nquad``: order of Gaussian quadrature (default: 51)
          - ``maxint``: maximum number of partial integral intervals
            (default: 40)
          - ``pts_per_dec``: points per decade; (default: 0)

            - If 0, no interpolation is used.
            - If > 0, interpolation is used.

          - ``diff_quad``: criteria when to swap to QUAD (only relevant if
            pts_per_dec>0) (default: 100)
          - ``a``: lower limit for QUAD (default: first interval from QWE)
          - ``b``: upper limit for QUAD (default: last interval from QWE)
          - ``limit``: limit for quad (default: maxint)

        - If ``ht='quad'``:

          - ``rtol``: relative tolerance (default: 1e-12)
          - ``atol``: absolute tolerance (default: 1e-20)
          - ``limit``: An upper bound on the number of subintervals used in the
            adaptive algorithm (default: 500)
          - ``a``: Minimum wavenumber (default 1e-6)
          - ``b``: Maximum wavenumber (default 0.1)
          - ``pts_per_dec``: points per decade (default: 40)

    ft : {'dlf', 'sin', 'cos', 'qwe', 'fftlog', 'fft'}, default: 'dlf'
        Only used if signal!=None. Flag to choose either the Digital Linear
        Filter method (Sine- or Cosine-Filter), the
        Quadrature-With-Extrapolation (QWE), the FFTLog, or the FFT for the
        Fourier transform. If 'dlf' it is 'sin' if signal>=0, else 'cos'.

    ftarg : dict, optional
        Only used if signal!=None. Possible parameters depends on the value for
        ``ft``:

        - If ``ft='dlf'``, ``'sin'``, or ``'cos'``:

          - ``dlf``: string of filter name in :mod:`empygrad.filters` or the
            filter method itself. (Default:
            ``empygrad.filters.Fourier().key_201_2012``)
          - ``pts_per_dec``: points per decade; (default: -1)

            - If 0: Standard DLF.
            - If < 0: Lagged Convolution DLF.
            - If > 0: Splined DLF


        - If ``ft='qwe'``:

          - ``rtol``: relative tolerance (default: 1e-8)
          - ``atol``: absolute tolerance (default: 1e-20)
          - ``nquad``: order of Gaussian quadrature (default: 21)
          - ``maxint``: maximum number of partial integral intervals
            (default: 200)
          - ``pts_per_dec``: points per decade (default: 20)
          - ``diff_quad``: criteria when to swap to QUAD (default: 100)
          - ``a``: lower limit for QUAD (default: first interval from QWE)
          - ``b``: upper limit for QUAD (default: last interval from QWE)
          - ``limit``: limit for quad (default: maxint)

        - If ``ft='fftlog'``:

          - ``pts_per_dec``: sampels per decade (default: 10)
          - ``add_dec``: additional decades [left, right] (default: [-2, 1])
          - ``q``: exponent of power law bias (default: 0); -1 <= q <= 1

        - If ``ft='fft'``:

          - ``dfreq``: Linear step-size of frequencies (default: 0.002)
          - ``nfreq``: Number of frequencies (default: 2048)
          - ``ntot``: Total number for FFT; difference between nfreq and ntot
            is padded with zeroes. This number is ideally a power of 2, e.g.
            2048 or 4096 (default: nfreq).
          - ``pts_per_dec``: points per decade (default: None)

          Padding can sometimes improve the result, not always. The default
          samples from 0.002 Hz - 4.096 Hz. If pts_per_dec is set to an
          integer, calculated frequencies are logarithmically spaced with the
          given number per decade, and then interpolated to yield the required
          frequencies for the FFT.

    xdirect : bool or None, default: False
        Direct field calculation (only if src and rec are in the same layer):

        - If True, direct field is calculated analytically in the frequency
          domain.
        - If False, direct field is calculated in the wavenumber domain.
        - If None, direct field is excluded from the calculation, and only
          reflected fields are returned (secondary field).

    loop : {None, 'freq', 'off'}, default: None
        Define if to calculate everything vectorized or if to loop over
        frequencies ('freq') or over offsets ('off'). It always loops over
        frequencies if ``ht='qwe'`` or if ``pts_per_dec=-1``. Calculating
        everything vectorized is fast for few offsets OR for few frequencies.
        However, if you calculate many frequencies for many offsets, it might
        be faster to loop over frequencies. Only comparing the different
        versions will yield the answer for your specific problem at hand!

    squeeze : bool, default: True
        If True, the output is squeezed. If False, the output will always be of
        ``ndim=3``, (nfreqtime, nrec, nsrc).

    bandpass : {dict, None}, default: None
        A dictionary containing any function that is applied to the
        frequency-domain result. The signature of the function must be
        ``func(inp, p_dict)``, where ``inp`` is the dictionary you provide, and
        ``p_dict`` is a dictionary that contains all parameters so far computed
        in empygrad ``[locals()]``. Any change to the frequency domain result
        must be done in-place, and the function does not return anything. Refer
        to the time-domain loop examples in the gallery. The dictionary must
        contain at least the keyword ``'func'``, containing the actual
        function, but can contain any other parameters too.

    jac : {None, str, list of str}, default: None
        Parameters w.r.t. which Jacobians are computed.  ``bipole`` currently
        supports only the eta-type parameters ``'res'``, ``'aniso'``,
        ``'epermH'``, ``'epermV'`` (geometry/position/offset Jacobians are
        available via :func:`dipole`).  The Jacobian is the integration-weighted
        sum of the point-dipole Jacobians, mirroring the primal integration.

        Restrictions: ``xdirect=True`` (analytical fullspace direct field) and
        current-density receivers (``mrec='j'``) are not supported with ``jac``.
        Time-domain Jacobians are supported (Fourier transform applied
        column-by-column).  If *jac* is a string an ndarray is returned; if a
        list, a ``dict {param: ndarray}``.


    Returns
    -------
    EM : EMArray, (nfreqtime, nrec, nsrc)
        Frequency- or time-domain EM field (depending on ``signal``):

        - If rec is electric, returns E [V/m].
        - If rec is magnetic, returns H [A/m].
        - If rec is ``b``, returns iωB | dB/dt [T/s].
        - If rec is ``j``, returns J [A/m²].

        EMArray is a subclassed ndarray with ``.pha`` and ``.amp`` attributes
        (only relevant for frequency-domain data).

        The shape of EM is (nfreqtime, nrec, nsrc). However, single dimensions
        are removed, unless you set ``squeeze=False``.

    J : ndarray or dict (only returned when *jac* is not ``None``)
        Jacobian(s), shape ``(nfreqtime, nrec, nlayer)`` per parameter (the
        ``nsrc`` axis is dropped when ``nsrc=1``).  Returned as a bare ndarray
        when *jac* is a string, or a ``dict {param: ndarray}`` when a list.


    Examples
    --------

    .. ipython::

       In [1]: import empygrad
          ...: import numpy as np
          ...: # x-directed dipole source: x0, x1, y0, y1, z0, z1
          ...: src = [-50, 50, 0, 0, 100, 100]
          ...: # x-directed dipole receiver-array: x, y, z, azimuth, dip
          ...: rec = [np.arange(1, 11)*500, np.zeros(10), 200, 0, 0]
          ...: # layer boundaries
          ...: depth = [0, 300, 1000, 1050]
          ...: # layer resistivities
          ...: res = [1e20, .3, 1, 50, 1]
          ...: # Frequency
          ...: freq = 1
          ...: # Calculate electric field due to an electric source at 1 Hz.
          ...: # [msrc = mrec = False (default)]
          ...: EMfield = empygrad.bipole(src, rec, depth, res, freq, verb=3)
       Out[1]:
          ...: :: empygrad START  ::  v2.0.0
          ...:
          ...:    depth       [m] :  0 300 1000 1050
          ...:    res     [Ohm.m] :  1E+20 0.3 1 50 1
          ...:    aniso       [-] :  1 1 1 1 1
          ...:    epermH      [-] :  1 1 1 1 1
          ...:    epermV      [-] :  1 1 1 1 1
          ...:    mpermH      [-] :  1 1 1 1 1
          ...:    mpermV      [-] :  1 1 1 1 1
          ...:    direct field    :  Comp. in wavenumber domain
          ...:    frequency  [Hz] :  1
          ...:    Hankel          :  DLF (Fast Hankel Transform)
          ...:      > Filter      :  key_201_2009
          ...:      > DLF type    :  Standard
          ...:    Loop over       :  None (all vectorized)
          ...:    Source type     : Electric field
          ...:    Receiver type   : Electric field
          ...:    Source(s)       :  1 dipole(s)
          ...:      > intpts      :  1 (as dipole)
          ...:      > length  [m] :  100
          ...:      > strength[A] :  0
          ...:      > x_c     [m] :  0
          ...:      > y_c     [m] :  0
          ...:      > z_c     [m] :  100
          ...:      > azimuth [°] :  0
          ...:      > dip     [°] :  0
          ...:    Receiver(s)     :  10 dipole(s)
          ...:      > x       [m] :  500 - 5000 : 10  [min-max; #]
          ...:      > y       [m] :  0 - 0 : 10  [min-max; #]
          ...:      > z       [m] :  200
          ...:      > azimuth [°] :  0
          ...:      > dip     [°] :  0
          ...:    Required ab's   :  11
          ...:
          ...: :: empygrad END; runtime = 0:00:00.005536 :: 1 kernel call(s)

       In [2]: EMfield[0]
       Out[2]: (1.6880934577857306e-10-3.083031298956568e-10j)

    """
    # Get kwargs with defaults.
    out = get_kwargs(
        [
            'verb', 'ht', 'htarg', 'ft', 'ftarg', 'xdirect', 'loop', 'squeeze',
            'bandpass',
        ],
        [2, 'dlf', {}, 'dlf', {}, False, None, True, None], kwargs,
    )
    verb, ht, htarg, ft, ftarg, xdirect, loop, squeeze, bandpass = out

    # Parse jac argument early so bad values fail before any computation.
    jac_params = _parse_jac(jac)

    # === 1.  LET'S START ============
    t0 = printstartfinish(verb)

    # === 2.  CHECK INPUT ============

    # Check times and Fourier Transform arguments and get required frequencies
    if signal is None:
        freq = freqtime
    else:
        outtime = check_time(freqtime, signal, ft, ftarg, verb, new=True)
        time, freq, ft, ftarg, signal = outtime

    # Check layer parameters
    model = check_model(depth, res, aniso, epermH, epermV, mpermH, mpermV,
                        xdirect, verb)
    depth, res, aniso, epermH, epermV, mpermH, mpermV, isfullspace = model

    # Check frequency => get etaH, etaV, zetaH, and zetaV
    frequency = check_frequency(freq, res, aniso, epermH, epermV, mpermH,
                                mpermV, verb)
    freq, etaH, etaV, zetaH, zetaV = frequency

    # Update etaH/etaV and zetaH/zetaV according to user-provided model
    if isinstance(res, dict) and 'func_eta' in res:
        etaH, etaV = res['func_eta'](res, locals())
    if isinstance(res, dict) and 'func_zeta' in res:
        zetaH, zetaV = res['func_zeta'](res, locals())

    # Check Hankel transform parameters
    ht, htarg = check_hankel(ht, htarg, verb)

    # Check loop
    loop_freq, loop_off = check_loop(loop, ht, htarg, verb)

    # Check src and rec, get flags if dipole or not
    # nsrcz/nrecz are number of unique src/rec-pole depths
    source = check_bipole(src, 'src', msrc, verb)
    src, nsrc, nsrcz, srcdipole, msrc, stype = source
    receiver = check_bipole(rec, 'rec', mrec, verb)
    rec, nrec, nrecz, recdipole, mrec, rtype = receiver

    # === Jacobian setup (eta-type parameters only) ===
    if jac_params is not None:
        unknown = set(jac_params) - _ALL_JAC_PARAMS
        if unknown:
            raise ValueError(
                f"Unknown Jacobian parameter(s): {sorted(unknown)}. "
                f"Supported: {sorted(_ALL_JAC_PARAMS)}.")
        unsupported = [p for p in jac_params if p not in _ETA_TYPE_PARAMS]
        if unsupported:
            raise NotImplementedError(
                f"bipole Jacobian currently supports only "
                f"{sorted(_ETA_TYPE_PARAMS)}; got unsupported {unsupported}. "
                "Use dipole() for geometry / position / offset Jacobians.")
        if xdirect is True:
            raise NotImplementedError(
                "bipole Jacobian is not implemented for xdirect=True "
                "(analytical fullspace direct field). Use xdirect=False/None.")
        if rtype == 'j':
            raise NotImplementedError(
                "bipole Jacobian is not implemented for current-density "
                "receivers (mrec='j').")

        # The Jacobian always uses standard DLF (see dipole()).
        if ht == 'dlf':
            htarg_jac = dict(htarg)
            htarg_jac['pts_per_dec'] = 0
        else:
            _, htarg_jac = check_hankel('dlf', {}, 0)
        dlf_filt = htarg_jac['dlf']

        # xdir is the resolved direct-field flag passed to the kernel; matches
        # the value fem() uses internally (xdirect=None -> True).
        xdir = True if xdirect is None else xdirect

        # eta seeds are position-independent — build once.
        jac_etaH_in, jac_etaV_in, eta_slices = _stacked_eta_seeds(
            jac_params, etaH, res, aniso, freq)
        n_params = jac_etaH_in.shape[2]
        jac_EM = np.zeros((freq.size, nrec*nsrc, n_params), dtype=etaH.dtype)

    # === 3. EM-FIELD CALCULATION ============

    # Pre-allocate output EM array
    EM = np.zeros((freq.size, nrec*nsrc), dtype=etaH.dtype)

    # Initialize kernel count, conv (only for QWE)
    # (how many times the wavenumber-domain kernel was calld)
    kcount = 0
    conv = True

    # Define some indices
    isrc = int(nsrc/nsrcz)  # this is either 1 or nsrc
    irec = int(nrec/nrecz)  # this is either 1 or nrec
    isrz = int(isrc*irec)   # this is either 1, nsrc, nrec, or nsrc*nrec

    # Warn flags
    warn_ecurrent = False
    warn_src_flux = False
    warn_rec_flux = False

    # The kernel handles only 1 ab with one srcz-recz combination at once.
    # Hence we have to loop over every different depth of src or rec, and
    # over all required ab's.
    for isz in range(nsrcz):  # Loop over source depths

        # Get this source
        srcazmdip = get_azm_dip(src, isz, nsrcz, srcpts, srcdipole, strength,
                                'src', verb)
        tsrc, srcazm, srcdip, srcg_w, srcpts, src_w = srcazmdip

        for irz in range(nrecz):  # Loop over receiver depths

            # Get this receiver
            recazmdip = get_azm_dip(rec, irz, nrecz, recpts, recdipole,
                                    strength, 'rec', verb)
            trec, recazm, recdip, recg_w, recpts, rec_w = recazmdip

            # Get required ab's
            ab_calc = get_abs(msrc, mrec, srcazm, srcdip, recazm, recdip, verb)

            # Pre-allocate temporary source-EM array for integration loop
            sEM = np.zeros((freq.size, isrz), dtype=etaH.dtype)
            if jac_params is not None:
                jac_sEM = np.zeros((freq.size, isrz, n_params),
                                   dtype=etaH.dtype)

            for isg in range(srcpts):  # Loop over src integration points

                # This integration source
                tisrc = [tsrc[0][isg::srcpts], tsrc[1][isg::srcpts],
                         tsrc[2][isg]]

                # Get layer number in which src resides
                lsrc, zsrc = get_layer_nr(tisrc, depth)

                # Pre-allocate temporary receiver EM arrays for integr. loop
                rEM = np.zeros((freq.size, isrz), dtype=etaH.dtype)
                if jac_params is not None:
                    jac_rEM = np.zeros((freq.size, isrz, n_params),
                                       dtype=etaH.dtype)

                for irg in range(recpts):  # Loop over rec integration pts
                    # Note, if source or receiver is a dipole, but horizontal
                    # (dip=0), then calculation could be sped up by not looping
                    # over the dipole elements, but calculate it all in one go.

                    # This integration receiver
                    tirec = [trec[0][irg::recpts], trec[1][irg::recpts],
                             trec[2][irg]]

                    # Get src-rec offsets and angles
                    off, angle = get_off_ang(tisrc, tirec, isrc, irec, verb)

                    # Get layer number in which rec resides
                    lrec, zrec = get_layer_nr(tirec, depth)

                    # Gather variables
                    finp = (off, angle, zsrc, zrec, lsrc, lrec, depth, freq,
                            etaH, etaV, zetaH, zetaV, xdirect, isfullspace, ht,
                            htarg, msrc, mrec, loop_freq, loop_off, conv)

                    # Pre-allocate temporary EM array for ab-loop
                    abEM = np.zeros((freq.size, isrz), dtype=etaH.dtype)
                    if jac_params is not None:
                        jac_abEM = np.zeros((freq.size, isrz, n_params),
                                            dtype=etaH.dtype)

                    for iab in ab_calc:  # Loop over required ab's

                        # Carry-out the frequency-domain calculation
                        out = fem(iab, *finp)

                        # Get geometrical scaling factor,
                        # broadcast to (irec, isrc)
                        tfact = np.ones((irec, isrc))*get_geo_fact(
                            iab, srcazm, srcdip, recazm, recdip, msrc, mrec
                        )
                        tfact_flat = tfact.ravel('F')

                        # Add field to EM with geometrical factor
                        abEM += out[0]*tfact_flat

                        # Update kernel count
                        kcount += out[1]

                        # Update conv (QWE convergence)
                        conv *= out[2]

                        # Jacobian contribution for this ab (same geo factor).
                        if jac_params is not None:
                            jcol = _fem_jac_columns(
                                iab, off, angle, zsrc, zrec, lsrc, lrec, depth,
                                freq, etaH, etaV, zetaH, zetaV, xdir,
                                isfullspace, msrc, mrec,
                                jac_etaH_in, jac_etaV_in, dlf_filt)
                            jac_abEM += jcol*tfact_flat[:, None]

                    # Multiply with eta of the rec-layer if ecurrent.
                    if rtype == 'j':
                        # Check eta at receiver level (only isotropic impl.).
                        if verb > 0 and etaH[0, lrec] != etaV[0, lrec]:
                            warn_ecurrent = True
                        abEM *= etaH[:, lrec, None]
                        # (jac for rtype='j' is guarded above.)

                    # Multiply with zeta of the rec-layer if flux.
                    elif rtype == 'b':
                        # Check zeta at receiver level (only isotropic impl.).
                        if verb > 0 and zetaH[0, lrec] != zetaV[0, lrec]:
                            warn_rec_flux = True
                        abEM *= zetaH[:, lrec, None]
                        # zetaH is independent of res/aniso/eperm -> scale jac.
                        if jac_params is not None:
                            jac_abEM *= zetaH[:, lrec, None, None]

                    # Add this receiver element, with weight from integration
                    rEM += abEM*recg_w[irg]
                    if jac_params is not None:
                        jac_rEM += jac_abEM*recg_w[irg]

                # Multiply with zeta of the src-layer if flux.
                if stype == 'b':
                    # Check zeta at source level (only isotropic impl.).
                    if verb > 0 and zetaH[0, lsrc] != zetaV[0, lsrc]:
                        warn_src_flux = True
                    rEM *= zetaH[:, lsrc, None]
                    if jac_params is not None:
                        jac_rEM *= zetaH[:, lsrc, None, None]

                # Add this source element, with weight from integration
                sEM += rEM*srcg_w[isg]
                if jac_params is not None:
                    jac_sEM += jac_rEM*srcg_w[isg]

            # Scale signal for src-strength and src/rec-lengths
            src_rec_w = 1
            if strength > 0:
                src_rec_w = np.repeat(src_w, irec)
                src_rec_w = src_rec_w*np.tile(rec_w, isrc)
            sEM *= src_rec_w
            if jac_params is not None and strength > 0:
                jac_sEM *= np.asarray(src_rec_w)[:, None]

            # Add this src-rec signal
            if nrec == nrecz:
                if nsrc == nsrcz:  # Case 1: Looped over each src and each rec
                    EM[:, isz*nrec+irz:isz*nrec+irz+1] = sEM
                    if jac_params is not None:
                        jac_EM[:, isz*nrec+irz:isz*nrec+irz+1, :] = jac_sEM
                else:              # Case 2: Looped over each rec
                    EM[:, irz:nsrc*nrec:nrec] = sEM
                    if jac_params is not None:
                        jac_EM[:, irz:nsrc*nrec:nrec, :] = jac_sEM
            else:
                if nsrc == nsrcz:  # Case 3: Looped over each src
                    EM[:, isz*nrec:nrec*(isz+1)] = sEM
                    if jac_params is not None:
                        jac_EM[:, isz*nrec:nrec*(isz+1), :] = jac_sEM
                else:              # Case 4: All in one go
                    EM = sEM
                    if jac_params is not None:
                        jac_EM = jac_sEM

    # In case of QWE/QUAD, print Warning if not converged
    conv_warning(conv, htarg, 'Hankel', verb)

    # Apply user-provided bandpass filter
    if isinstance(bandpass, dict) and 'func' in bandpass:
        bandpass['func'](bandpass, locals())

    # Do f->t transform if required
    if signal is not None:
        # Jacobian f->t (chain rule: J_t = FT[J_f]) — before EM is overwritten
        # so the freq-domain jac_EM is still available.  The 2nd tem() arg is
        # only used for its size (number of offset columns).
        if jac_params is not None:
            jac_EM_time = np.zeros((time.size, jac_EM.shape[1], n_params))
            for k in range(n_params):
                jac_EM_time[:, :, k], _ = tem(
                    jac_EM[:, :, k], jac_EM[0, :, k], freq, time, signal,
                    ft, ftarg)
            jac_EM = jac_EM_time

        EM, conv = tem(EM, EM[0, :], freq, time, signal, ft, ftarg)

        # In case of QWE/QUAD, print Warning if not converged
        conv_warning(conv, ftarg, 'Fourier', verb)

    # Reshape for number of sources
    EM = EM.reshape((-1, nrec, nsrc), order='F')
    if squeeze:
        EM = np.squeeze(EM)

    # Reshape Jacobian to (ntime_or_nfreq, nrec, nsrc, n_params); drop nsrc when
    # nsrc==1 (matching dipole's convention; the param axis stays last).
    if jac_params is not None:
        jac_EM = jac_EM.reshape((-1, nrec, nsrc, n_params), order='F')
        if nsrc == 1:
            jac_EM = jac_EM[:, :, 0, :]

    # Raise warnings
    if verb > 0:
        if warn_ecurrent:
            print("* WARNING :: `etaH != etaV` at receiver level, "
                  "only `etaH` considered for e-current density.")
        if warn_src_flux:
            print("* WARNING :: `zetaH != zetaV` at source level, "
                  "only `zetaH` considered for magnetic flux.")
        if warn_rec_flux:
            print("* WARNING :: `zetaH != zetaV` at receiver level, "
                  "only `zetaH` considered for magnetic flux.")

    # === 4.  FINISHED ============
    printstartfinish(verb, t0, kcount)

    EM_out = EMArray(EM)
    if jac_params is None:
        return EM_out

    # Slice the stacked Jacobian into per-parameter arrays.
    jac_out = {p: jac_EM[..., sl] for p, sl in eta_slices.items()}
    if isinstance(jac, str):
        return EM_out, jac_out[jac]
    return EM_out, jac_out


# ---------------------------------------------------------------------------
# Jacobian parameter classification
# ---------------------------------------------------------------------------

# Parameters whose Jacobian flows through d(etaH, etaV)/d(param) seeds.
_ETA_TYPE_PARAMS = frozenset({'res', 'aniso', 'epermH', 'epermV'})

# Parameters whose Jacobian flows through d(zetaH, zetaV)/d(param) seeds
# (magnetic permeability).  These do NOT flow through etaH/etaV; they enter the
# Gamma formulas, the TE reflection seed, and the TE ab-factor scaling.
_ZETA_TYPE_PARAMS = frozenset({'mpermH', 'mpermV'})

# Parameters whose Jacobian flows through depth/thickness perturbations.
_GEO_DEPTH_PARAMS = frozenset({'depth', 'thickness'})
_GEO_TYPE_PARAMS  = _GEO_DEPTH_PARAMS  # legacy alias

# Source-position parameters.
_SRC_POS_PARAMS = frozenset({'src_x', 'src_y', 'src_z'})

# Receiver-position parameters.
_REC_POS_PARAMS = frozenset({'rec_z'})

# Horizontal source-receiver offset.  Unlike all other parameters, the offset
# Jacobian is a pure post-processing of the *primal* wavenumber-domain arrays
# (it enters only through the Bessel functions in the Hankel transform), so it
# does not flow through the kernel Jacobian machinery at all.
_OFFSET_PARAMS = frozenset({'off'})

_ALL_JAC_PARAMS = (_ETA_TYPE_PARAMS | _ZETA_TYPE_PARAMS | _GEO_TYPE_PARAMS
                   | _SRC_POS_PARAMS | _REC_POS_PARAMS | _OFFSET_PARAMS)


def _parse_jac(jac):
    """Normalise the ``jac`` argument to ``None`` or a list of strings."""
    if jac is None:
        return None
    if isinstance(jac, str):
        return [jac]
    return list(jac)


def _stacked_depth_seeds(depth_params, n_interfaces):
    """Compute jac_depth_lower for depth/thickness parameters.

    Parameters
    ----------
    depth_params : list of str
        Ordered subset of ``_GEO_DEPTH_PARAMS`` to include.
    n_interfaces : int
        Number of free interface positions (= nlayer - 1).

    Returns
    -------
    jac_depth_lower : float64 ndarray, shape (n_interfaces, n_total)
        ``jac_depth_lower[n, k] = d(depth_user[n]) / d(param_k)``.
        For 'depth' params this is the identity block; for 'thickness'
        (not yet implemented) it would encode layer thicknesses.
    param_slices : dict
        Maps each parameter name to its ``slice`` in the last axis.
    """
    seeds = []
    param_slices = {}
    col = 0

    for p in depth_params:
        if p == 'depth':
            # d(depth_user[n])/d(depth_user[k]) = delta(n, k) → identity
            jac = np.eye(n_interfaces)
            seeds.append(jac)
            param_slices['depth'] = slice(col, col + n_interfaces)
            col += n_interfaces
        elif p == 'thickness':
            raise NotImplementedError(
                "Jacobian w.r.t. 'thickness' is not yet implemented. "
                "Use 'depth' (interface positions) instead.")

    if seeds:
        return np.concatenate(seeds, axis=1), param_slices
    return np.zeros((n_interfaces, 0)), param_slices


def _stacked_eta_seeds(eta_params, etaH, res, aniso, freq):
    """Compute stacked d(etaH, etaV)/d(param) seed matrices.

    Parameters
    ----------
    eta_params : list of str
        Ordered subset of ``_ETA_TYPE_PARAMS`` to include.
    etaH : complex ndarray, shape (nfreq, nlayer)
        Primal etaH — used only to read nfreq, nlayer, and dtype.
    res, aniso : 1-D float arrays, length nlayer
        Layer resistivities and anisotropy ratios (after ``check_model``).
    freq : 1-D float array, length nfreq
        Frequencies (Hz).  Needed for the frequency-dependent seeds of
        ``epermH`` and ``epermV``.

    Returns
    -------
    jac_etaH, jac_etaV : complex ndarray, shape (nfreq, nlayer, n_total)
        Stacked seed matrices.  ``n_total = nlayer * len(eta_params)``.
    param_slices : dict
        Maps each parameter name to its ``slice`` in the last axis.
    """
    _EPS0 = 8.8541878128e-12   # vacuum permittivity (F/m)
    nfreq, nlayer = etaH.shape
    res   = np.asarray(res,   dtype=float)
    aniso = np.asarray(aniso, dtype=float)
    idx   = np.arange(nlayer)

    seeds_H, seeds_V, param_slices = [], [], {}
    col = 0

    for p in eta_params:
        j_H = np.zeros((nfreq, nlayer, nlayer), dtype=etaH.dtype)
        j_V = np.zeros((nfreq, nlayer, nlayer), dtype=etaH.dtype)

        if p == 'res':
            # etaH = iw*eps0*epermH + 1/res  => d(etaH)/d(res[k]) = -1/res[k]^2
            # etaV = iw*eps0*epermV + 1/(res*aniso^2)  => d(etaV)/d(res[k]) = -1/(res[k]^2 * aniso[k]^2)
            diag_H = -1.0 / res**2
            diag_V = -1.0 / (res**2 * aniso**2)
            j_H[:, idx, idx] = diag_H
            j_V[:, idx, idx] = diag_V

        elif p == 'aniso':
            # etaV = iw*eps0*epermV + sigma_h/aniso^2;  etaH independent of aniso
            # d(etaV[i,j])/d(aniso[k]) = -2/(res[k]*aniso[k]^3) * delta(j,k)
            diag_v = -2.0 / (res * aniso**3)
            j_V[:, idx, idx] = diag_v
            # j_H stays zero

        elif p == 'epermH':
            # etaH = 1/res + s*eps0*epermH  =>  d(etaH[i,n])/d(epermH[n]) = s[i]*eps0
            # etaV independent of epermH
            for i_f in range(nfreq):
                sval = 2j * np.pi * freq[i_f]
                j_H[i_f, idx, idx] = sval * _EPS0
            # j_V stays zero

        elif p == 'epermV':
            # etaV = 1/(res*aniso^2) + s*eps0*epermV  =>  d(etaV[i,n])/d(epermV[n]) = s[i]*eps0
            # etaH independent of epermV
            for i_f in range(nfreq):
                sval = 2j * np.pi * freq[i_f]
                j_V[i_f, idx, idx] = sval * _EPS0
            # j_H stays zero

        else:
            raise NotImplementedError(
                f"Jacobian w.r.t. '{p}' is not yet implemented. "
                f"Supported eta-type parameters: {sorted(_ETA_TYPE_PARAMS)}.")

        seeds_H.append(j_H)
        seeds_V.append(j_V)
        param_slices[p] = slice(col, col + nlayer)
        col += nlayer

    jac_etaH = np.concatenate(seeds_H, axis=2)
    jac_etaV = np.concatenate(seeds_V, axis=2)
    return jac_etaH, jac_etaV, param_slices


def _stacked_zeta_seeds(zeta_params, etaH, freq):
    """Compute stacked d(zetaH, zetaV)/d(param) seed matrices (magnetic perm.).

    zetaH = i*omega*mu0*mpermH  =>  d(zetaH[i,n])/d(mpermH[n]) = s[i]*mu0
    zetaV = i*omega*mu0*mpermV  =>  d(zetaV[i,n])/d(mpermV[n]) = s[i]*mu0

    Parameters
    ----------
    zeta_params : list of str
        Ordered subset of ``_ZETA_TYPE_PARAMS`` to include.
    etaH : complex ndarray, shape (nfreq, nlayer)
        Used only for nfreq, nlayer, dtype.
    freq : 1-D float array, length nfreq
        Frequencies (Hz).

    Returns
    -------
    jac_zetaH, jac_zetaV : complex ndarray, shape (nfreq, nlayer, n_total)
        Stacked seed matrices (``n_total = nlayer * len(zeta_params)``).
    param_slices : dict
        Maps each parameter name to its ``slice`` in the last axis.
    """
    _MU0 = 4e-7 * np.pi    # vacuum permeability (H/m)
    nfreq, nlayer = etaH.shape
    idx = np.arange(nlayer)

    seeds_zH, seeds_zV, param_slices = [], [], {}
    col = 0

    for p in zeta_params:
        j_zH = np.zeros((nfreq, nlayer, nlayer), dtype=etaH.dtype)
        j_zV = np.zeros((nfreq, nlayer, nlayer), dtype=etaH.dtype)

        if p == 'mpermH':
            for i_f in range(nfreq):
                sval = 2j * np.pi * freq[i_f]
                j_zH[i_f, idx, idx] = sval * _MU0
            # j_zV stays zero
        elif p == 'mpermV':
            for i_f in range(nfreq):
                sval = 2j * np.pi * freq[i_f]
                j_zV[i_f, idx, idx] = sval * _MU0
            # j_zH stays zero
        else:
            raise NotImplementedError(
                f"Jacobian w.r.t. '{p}' is not yet implemented. "
                f"Supported zeta-type parameters: {sorted(_ZETA_TYPE_PARAMS)}.")

        seeds_zH.append(j_zH)
        seeds_zV.append(j_zV)
        param_slices[p] = slice(col, col + nlayer)
        col += nlayer

    jac_zetaH = np.concatenate(seeds_zH, axis=2)
    jac_zetaV = np.concatenate(seeds_zV, axis=2)
    return jac_zetaH, jac_zetaV, param_slices


def _offset_derivative(PJ0, PJ1, PJ0b, lambd, off, filt, ang_fact, ab):
    r"""Return ``d(EM)/d(off)``: the horizontal-offset derivative of the field.

    The offset ``r`` enters the forward model *only* through the Bessel
    functions :math:`J_\nu(\lambda r)` in the Hankel transform.  Using the
    Bessel-derivative identity
    :math:`\partial_r J_\nu(\lambda r) = \lambda J_{\nu-1}(\lambda r)
    - (\nu/r) J_\nu(\lambda r)`, the derivative of a Hankel transform of order
    ``nu`` is

    .. math::
        \frac{\partial}{\partial r} H_\nu[f](r)
        = H_{\nu-1}[\lambda f](r) - \frac{\nu}{r} H_\nu[f](r).

    The primal field is assembled by :func:`empymod.transform.dlf` from
    ``(PJ0, PJ1, PJ0b)`` with PJ0/PJ0b mapped to :math:`J_0` and PJ1 to
    :math:`J_1` (or :math:`J_2` for ``ab`` in the J2 set).  Applying the rule
    above to each Bessel component yields the offset derivative directly from
    the primal arrays — no kernel re-evaluation.

    Parameters mirror :func:`empymod.transform.dlf` (standard DLF,
    ``pts_per_dec=0``).  ``PJ*`` have shape ``(nfreq, noff, nlambda)`` (or
    ``None``); ``lambd`` is ``(noff, nlambda)``; ``off`` and ``ang_fact`` are
    ``(noff,)``.  Returns ``(nfreq, noff)``.
    """
    j0, j1 = filt.j0, filt.j1
    ref = PJ0 if PJ0 is not None else (PJ1 if PJ1 is not None else PJ0b)
    if ref is None:        # ab = 36/63: zero field, zero derivative
        return np.zeros((1, off.size), dtype=complex)

    nfreq = ref.shape[0]
    r   = off[None, :]              # (1, noff)
    lam = lambd[None, :, :]         # (1, noff, nlambda)

    def H0(X):                      # H_0[X](r) = (X . j0) / r
        return (X @ j0) / r
    def H1(X):                      # H_1[X](r) = (X . j1) / r
        return (X @ j1) / r

    dG = np.zeros((nfreq, off.size), dtype=ref.dtype)

    # Angle-independent J0 part:  B = H_0[PJ0];  B' = -H_1[lambda*PJ0]
    if PJ0 is not None:
        dG += -H1(lam * PJ0)

    # Angle-dependent part A; A' differs for J1 vs J2 (the J2 set carries an
    # extra 1/r in the primal, see empymod.transform.dlf).
    A_prime = np.zeros((nfreq, off.size), dtype=ref.dtype)
    j2_ab = ab in (11, 12, 21, 22, 14, 24, 15, 25)
    if not j2_ab:
        # A = H_1[PJ1] + H_0[PJ0b]
        if PJ1 is not None:
            A_prime += H0(lam * PJ1) - H1(PJ1) / r
        if PJ0b is not None:
            A_prime += -H1(lam * PJ0b)
    else:
        # A = H_1[PJ1]/r + H_0[PJ0b]   (the 1/r encodes the J2 structure)
        if PJ1 is not None:
            A_prime += H0(lam * PJ1) / r - 2.0 * H1(PJ1) / r**2
        if PJ0b is not None:
            A_prime += -H1(lam * PJ0b)

    dG += ang_fact * A_prime
    return dG


def _fem_jac_columns(ab, off, angle, zsrc, zrec, lsrc, lrec, depth, freq,
                     etaH, etaV, zetaH, zetaV, xdir, isfullspace,
                     msrc, mrec, jac_etaH_in, jac_etaV_in, dlf_filt):
    r"""Jacobian of the frequency-domain field for a single ``ab`` (bipole).

    Mirrors the wavenumber-domain part of :func:`fem`, but propagates the
    eta-seeds ``(jac_etaH_in, jac_etaV_in)`` through :func:`kernel.wavenumber`
    and DLF-transforms each parameter column.  Returns ``jac_fEM`` of shape
    ``(nfreq, noff, n_params)``.

    Only the wavenumber-domain (reflected + optionally direct) contribution is
    included.  The analytical fullspace direct field (``xdirect=True``) is not
    handled here — :func:`bipole` guards that case.  ``xdir`` is the resolved
    direct-field flag (``xdirect=None`` -> ``True``), matching what :func:`fem`
    passes to the Hankel transform.
    """
    n_params = jac_etaH_in.shape[2]
    jac_fEM = np.zeros((freq.size, off.size, n_params), dtype=etaH.dtype)

    if ab in (36, ):           # field (and Jacobian) is identically zero
        return jac_fEM
    if isfullspace and xdir:   # no wavenumber-domain contribution
        return jac_fEM

    ang_fact = kernel.angle_factor(angle, ab, msrc, mrec)
    lambd, _ = transform.get_dlf_points(dlf_filt, off, 0)

    _, _, _, jPJ0, jPJ1, jPJ0b = kernel.wavenumber(
        zsrc, zrec, lsrc, lrec, depth, etaH, etaV, zetaH, zetaV,
        lambd, ab, xdir, msrc, mrec, jac_etaH_in, jac_etaV_in)

    for k in range(n_params):
        jpj = (
            jPJ0[:, :, :, k]  if jPJ0  is not None else None,
            jPJ1[:, :, :, k]  if jPJ1  is not None else None,
            jPJ0b[:, :, :, k] if jPJ0b is not None else None,
        )
        jac_fEM[:, :, k] = transform.dlf(
            jpj, lambd, off, dlf_filt, 0,
            ang_fact=ang_fact, ab=ab, int_pts=None)

    return jac_fEM


def dipole(src, rec, depth, res, freqtime, signal=None, ab=11, aniso=None,
           epermH=None, epermV=None, mpermH=None, mpermV=None, jac=None,
           **kwargs):
    r"""Return EM fields due to infinitesimal small EM dipoles.

    Calculate the electromagnetic frequency- or time-domain field due to
    infinitesimal small electric or magnetic dipole source(s), measured by
    infinitesimal small electric or magnetic dipole receiver(s); sources and
    receivers are directed along the principal directions x, y, or z, and all
    sources are at the same depth, as well as all receivers are at the same
    depth.

    Use the functions :func:`bipole` to calculate dipoles with arbitrary angles
    or dipoles of finite length and arbitrary angle.

    The function :func:`dipole` could be replaced by :func:`bipole` (all there
    is to do is translate ``ab`` into ``msrc``, ``mrec``, ``azimuth``'s and
    ``dip``'s). However, :func:`dipole` is kept separately to serve as an
    example of a simple modelling routine that can serve as a template.


    See Also
    --------
    :func:`bipole` : EM fields due to arbitrary rotated, finite length EM
                     dipoles.
    :func:`loop` : EM fields due to a magnetic source loop.


    Parameters
    ----------
    src, rec : list of floats or arrays
        Source and receiver coordinates [x, y, z] (m):

        For `N` sources or receivers, the x- and y-coordinates must be of size
        `N` or 1 (in the latter case it will be expanded to `N`); z is always a
        single value.

        Sources or receivers placed on a layer interface are considered in the
        upper layer.

    depth : list
        Absolute layer interfaces z (m); #depth = #res - 1
        (excluding +/- infinity).

    res : array_like
        Horizontal resistivities rho_h (Ohm.m); #res = #depth + 1.

        Alternatively, res can be a dictionary. See the main manual of empygrad
        too see how to exploit this hook to re-calculate etaH, etaV, zetaH, and
        zetaV, which can be used to, for instance, use the Cole-Cole model for
        IP.

    freqtime : array_like
        Frequencies f (Hz) if ``signal==None``, else times t (s); (f, t > 0).

    signal : {None, -1, 0, 1, dict}, default: None
        Source signal:

        - None: Frequency-domain response
        - -1 : Switch-off time-domain response
        - 0 : Impulse time-domain response
        - +1 : Switch-on time-domain response
        - dict : Arbitrary waveform

          For an arbitrary waveform, the dictionary must contain the following
          keyword-value pairs:

          - nodes : array_like
              Nodes of the waveform.
          - amplitudes : array_like
              Amplitudes (current) of the waveform.
          - signal : {-1, 0, 1}, default: 0
              Signal that is convolved with the waveform.
          - nquad : int, default: 3
              Number of quadrature points for the waveform segments.

    ab : int, default: 11
        Source-receiver configuration.

        +---------------+-------+------+------+------+------+------+------+
        |                       | electric  source   | magnetic source    |
        +===============+=======+======+======+======+======+======+======+
        |                       | **x**| **y**| **z**| **x**| **y**| **z**|
        +---------------+-------+------+------+------+------+------+------+
        |               | **x** |  11  |  12  |  13  |  14  |  15  |  16  |
        + **electric**  +-------+------+------+------+------+------+------+
        |               | **y** |  21  |  22  |  23  |  24  |  25  |  26  |
        + **receiver**  +-------+------+------+------+------+------+------+
        |               | **z** |  31  |  32  |  33  |  34  |  35  |  36  |
        +---------------+-------+------+------+------+------+------+------+
        |               | **x** |  41  |  42  |  43  |  44  |  45  |  46  |
        + **magnetic**  +-------+------+------+------+------+------+------+
        |               | **y** |  51  |  52  |  53  |  54  |  55  |  56  |
        + **receiver**  +-------+------+------+------+------+------+------+
        |               | **z** |  61  |  62  |  63  |  64  |  65  |  66  |
        +---------------+-------+------+------+------+------+------+------+

    aniso : array_like, default: ones
        Anisotropies lambda = sqrt(rho_v/rho_h) (-); #aniso = #res.

    epermH, epermV : array_like, default: ones
        Relative horizontal/vertical electric permittivities
        epsilon_h/epsilon_v (-); #epermH = #epermV = #res. If epermH is
        provided but not epermV, isotropic behaviour is assumed.

    mpermH, mpermV : array_like, default: ones
        Relative horizontal/vertical magnetic permeabilities mu_h/mu_v (-);
        #mpermH = #mpermV = #res. If mpermH is provided but not mpermV,
        isotropic behaviour is assumed.

    verb : {0, 1, 2, 3, 4}, default: 2
        Level of verbosity:

        - 0: Print nothing.
        - 1: Print warnings.
        - 2: Print additional runtime and kernel calls
        - 3: Print additional start/stop, condensed parameter information.
        - 4: Print additional full parameter information

    ht, htarg, ft, ftarg, xdirect, loop : settings, optinal
        See docstring of :func:`bipole` for a description.

    squeeze : bool, default: True
        If True, the output is squeezed. If False, the output will always be of
        ``ndim=3``, (nfreqtime, nrec, nsrc).

    bandpass : {dict, None}, default: None
        A dictionary containing any function that is applied to the
        frequency-domain result. The signature of the function must be
        ``func(inp, p_dict)``, where ``inp`` is the dictionary you provide, and
        ``p_dict`` is a dictionary that contains all parameters so far computed
        in empygrad ``[locals()]``. Any change to the frequency domain result
        must be done in-place, and the function does not return anything. Refer
        to the time-domain loop examples in the gallery. The dictionary must
        contain at least the keyword ``'func'``, containing the actual
        function, but can contain any other parameters too.

    jac : {None, str, list of str}, default: None
        Parameters w.r.t. which Jacobians are computed.  Supported values:

        - ``None`` : return only *EM* (no Jacobian overhead).
        - ``'res'`` : ``d(EM)/d(res_k)``, shape ``(nfreq, nrec, nlayer)``.
        - ``'aniso'`` : ``d(EM)/d(aniso_k)``, shape ``(nfreq, nrec, nlayer)``.
        - ``'epermH'`` : ``d(EM)/d(epermH_k)``, shape ``(nfreq, nrec, nlayer)``.
        - ``'epermV'`` : ``d(EM)/d(epermV_k)``, shape ``(nfreq, nrec, nlayer)``.
        - ``'mpermH'`` : ``d(EM)/d(mpermH_k)``, shape ``(nfreq, nrec, nlayer)``.
          Not supported in MM mode (magnetic source AND receiver).
        - ``'mpermV'`` : ``d(EM)/d(mpermV_k)``, shape ``(nfreq, nrec, nlayer)``.
          Not supported in MM mode (magnetic source AND receiver).
        - ``'depth'`` : ``d(EM)/d(depth[k])``, shape ``(nfreq, nrec, n_interfaces)``
          where ``n_interfaces = len(depth)``; requires ``signal=None``, ``ht='dlf'``.
        - ``'thickness'`` : not yet implemented.
        - ``'src_z'`` : ``d(EM)/d(z_src)``, shape ``(nfreq, nrec, 1)``.
          Not supported for ME mode (magnetic receiver, electric source).
        - ``'rec_z'`` : ``d(EM)/d(z_rec)``, shape ``(nfreq, nrec, 1)``.
          Not supported for ME mode (magnetic receiver, electric source).
        - ``'off'`` : ``d(EM)/d(r)`` w.r.t. the radial source-receiver offset
          (angle held fixed), shape ``(nfreq, nrec, 1)``.  Computed from the
          Bessel-derivative of the Hankel transform applied to the primal
          wavenumber arrays — does not flow through the kernel Jacobian.
        - ``'src_x'``, ``'src_y'`` : not yet implemented.

        If *jac* is a single string, the Jacobian is returned as an ndarray.
        If *jac* is a list, a ``dict {param: ndarray}`` is returned.

        The Jacobian always uses DLF internally for the Hankel transform,
        regardless of the ``ht`` setting.  ``ht='qwe'`` and ``ht='quad'``
        are fully supported for the primal; the Jacobian is computed with
        default DLF quadrature, which is accurate for well-conditioned models.
        Time-domain Jacobians (``signal != None``) apply the Fourier transform
        column-by-column (chain rule: ``J_t = FT[J_f]``).


    Returns
    -------
    EM : EMArray, (nfreqtime, nrec, nsrc)
        Frequency- or time-domain EM field (depending on ``signal``):

        - If rec is electric, returns E [V/m].
        - If rec is magnetic, returns H [A/m].

        EMArray is a subclassed ndarray with ``.pha`` and ``.amp`` attributes
        (only relevant for frequency-domain data).

        The shape of EM is (nfreqtime, nrec, nsrc). However, single dimensions
        are removed.

    J : ndarray or dict (only returned when *jac* is not ``None``)
        Jacobian(s).  Shape ``(nfreq, nrec, nlayer)`` per parameter.
        Returned as a bare ndarray when *jac* is a string, or as a
        ``dict {param: ndarray}`` when *jac* is a list.


    Examples
    --------

    .. ipython::

       In [1]: import empygrad
          ...: import numpy as np
          ...: src = [0, 0, 100]
          ...: rec = [np.arange(1, 11)*500, np.zeros(10), 200]
          ...: depth = [0, 300, 1000, 1050]
          ...: res = [1e20, .3, 1, 50, 1]
          ...: EMfield = empygrad.dipole(
          ...:         src, rec, depth, res, freqtime=1, verb=1)
          ...: EMfield[0]
       Out[1]: (1.6880934577857306e-10-3.083031298956568e-10j)

    """
    # Get kwargs with defaults.
    out = get_kwargs(
        [
            'verb', 'ht', 'htarg', 'ft', 'ftarg', 'xdirect', 'loop', 'squeeze',
            'bandpass',
        ],
        [2, 'dlf', {}, 'dlf', {}, False, None, True, None], kwargs,
    )
    verb, ht, htarg, ft, ftarg, xdirect, loop, squeeze, bandpass = out

    # Parse jac argument early so bad values fail before any computation.
    jac_params = _parse_jac(jac)

    # === 1.  LET'S START ============
    t0 = printstartfinish(verb)

    # === 2.  CHECK INPUT ============

    # Check times and Fourier Transform arguments, get required frequencies
    # (freq = freqtime if `signal=None`)
    if signal is not None:
        out = check_time(freqtime, signal, ft, ftarg, verb, True)
        time, freq, ft, ftarg, signal = out
    else:
        freq = freqtime

    # Check layer parameters
    model = check_model(depth, res, aniso, epermH, epermV, mpermH, mpermV,
                        xdirect, verb)
    depth, res, aniso, epermH, epermV, mpermH, mpermV, isfullspace = model

    # Check frequency => get etaH, etaV, zetaH, and zetaV
    frequency = check_frequency(freq, res, aniso, epermH, epermV, mpermH,
                                mpermV, verb)
    freq, etaH, etaV, zetaH, zetaV = frequency

    # Update etaH/etaV and zetaH/zetaV according to user-provided model
    if isinstance(res, dict) and 'func_eta' in res:
        etaH, etaV = res['func_eta'](res, locals())
    if isinstance(res, dict) and 'func_zeta' in res:
        zetaH, zetaV = res['func_zeta'](res, locals())

    # Check Hankel transform parameters
    ht, htarg = check_hankel(ht, htarg, verb)

    # Check loop
    loop_freq, loop_off = check_loop(loop, ht, htarg, verb)

    # Check src-rec configuration
    # => Get flags if src or rec or both are magnetic (msrc, mrec)
    ab_calc, msrc, mrec = check_ab(ab, verb)

    # Check src and rec
    src, nsrc = check_dipole(src, 'src', verb)
    rec, nrec = check_dipole(rec, 'rec', verb)

    # Get offsets and angles (off, angle)
    off, angle = get_off_ang(src, rec, nsrc, nrec, verb)

    # Get layer number in which src and rec reside (lsrc/lrec)
    lsrc, zsrc = get_layer_nr(src, depth)
    lrec, zrec = get_layer_nr(rec, depth)

    # === 3. EM-FIELD CALCULATION ============

    # Collect variables for fem
    inp = (ab_calc, off, angle, zsrc, zrec, lsrc, lrec, depth, freq, etaH,
           etaV, zetaH, zetaV, xdirect, isfullspace, ht, htarg, msrc, mrec,
           loop_freq, loop_off)
    EM, kcount, conv = fem(*inp)

    # In case of QWE/QUAD, print Warning if not converged
    conv_warning(conv, htarg, 'Hankel', verb)

    # Apply user-provided bandpass filter
    if isinstance(bandpass, dict) and 'func' in bandpass:
        bandpass['func'](bandpass, locals())

    # Do f->t transform if required
    if signal is not None:
        EM, conv = tem(EM, off, freq, time, signal, ft, ftarg)

        # In case of QWE/QUAD, print Warning if not converged
        conv_warning(conv, ftarg, 'Fourier', verb)

    # Reshape for number of sources
    EM = EM.reshape((-1, nrec, nsrc), order='F')
    if squeeze:
        EM = np.squeeze(EM)

    # === 4.  FINISHED ============
    printstartfinish(verb, t0, kcount)

    EM_out = EMArray(EM)

    if jac_params is None:
        return EM_out

    # === 5. JACOBIAN COMPUTATION ============

    # Validate requested parameters.
    unknown = set(jac_params) - _ALL_JAC_PARAMS
    if unknown:
        raise ValueError(
            f"Unknown Jacobian parameter(s): {sorted(unknown)}. "
            f"Supported: {sorted(_ALL_JAC_PARAMS)}.")

    src_horiz_params = [p for p in jac_params if p in {'src_x', 'src_y'}]
    if src_horiz_params:
        raise NotImplementedError(
            f"Jacobian w.r.t. {src_horiz_params} is not yet implemented.")

    has_src_z = 'src_z' in jac_params
    has_rec_z = 'rec_z' in jac_params
    has_off   = 'off' in jac_params   # offset derivative — handled separately

    eta_params   = [p for p in jac_params if p in _ETA_TYPE_PARAMS]
    zeta_params  = [p for p in jac_params if p in _ZETA_TYPE_PARAMS]
    depth_params = [p for p in jac_params if p in _GEO_DEPTH_PARAMS]

    # Magnetic-permeability Jacobians: MM mode (both src and rec magnetic) is
    # not supported — the eta<->zeta duality swap makes the seed bookkeeping
    # intricate, and the only MM ab's use the trivial ab-factor block.
    if zeta_params and msrc and mrec:
        raise NotImplementedError(
            f"Jacobian w.r.t. {zeta_params} is not implemented for MM mode "
            "(magnetic source AND magnetic receiver).")

    # The Jacobian always uses DLF for the Hankel transform regardless of the
    # ht setting for the primal.  Reason: kernel.wavenumber() returns PJ arrays
    # at DLF quadrature points; transform.dlf() is the only post-processor that
    # takes pre-computed PJ arrays.  hankel_qwe / hankel_quad integrate the
    # kernel internally and cannot accept pre-computed PJ arrays.
    # For ht='qwe'/'quad', the primal uses QWE/QUAD while the Jacobian uses
    # default DLF — both are accurate for well-conditioned models.
    # Always use standard DLF (pts_per_dec=0) for the Jacobian.  This ensures
    # int_pts=None, which makes loop_off slicing straightforward and avoids
    # splined-DLF interpolation complexity in the loop branches.
    if ht == 'dlf':
        htarg_jac = dict(htarg)
        htarg_jac['pts_per_dec'] = 0   # override to standard (non-splined) DLF
    else:
        _, htarg_jac = check_hankel('dlf', {}, 0)

    ang_fact = kernel.angle_factor(angle, ab_calc, msrc, mrec)
    lambd, int_pts = transform.get_dlf_points(
        htarg_jac['dlf'], off, htarg_jac['pts_per_dec'])
    # int_pts is always None here (pts_per_dec=0)

    # --- Build the unified kernel seed arrays, column block by column block ---
    # Five seed streams are aligned on a single parameter (column) axis:
    #   jac_etaH_in/jac_etaV_in  (nfreq, nlayer, n_params)
    #   jac_zetaH_in/jac_zetaV_in (nfreq, nlayer, n_params)  [magnetic perm.]
    #   jac_dlo_in               (n_interfaces, n_params)    [depth]
    # plus per-column src_z/rec_z indicators (handled after).
    nlayer       = etaH.shape[1]
    n_interfaces = depth.size - 1   # depth[0] = -inf; free interfaces are depth[1:]

    bl_eH, bl_eV, bl_zH, bl_zV, bl_dlo = [], [], [], [], []
    all_slices = {}
    col = 0

    def _zero_eta(n):
        return np.zeros((freq.size, nlayer, n), dtype=etaH.dtype)

    def _add_block(jeH, jeV, jzH, jzV, jdlo, sl):
        """Append one parameter group's seed blocks and offset its slices."""
        nonlocal col
        n = jeH.shape[2]
        bl_eH.append(jeH);  bl_eV.append(jeV)
        bl_zH.append(jzH);  bl_zV.append(jzV)
        bl_dlo.append(jdlo)
        for name, s in sl.items():
            all_slices[name] = slice(col + s.start, col + s.stop)
        col += n

    # eta group (res / aniso / epermH / epermV)
    if eta_params:
        jeH, jeV, sl = _stacked_eta_seeds(eta_params, etaH, res, aniso, freq)
        n = jeH.shape[2]
        _add_block(jeH, jeV, _zero_eta(n), _zero_eta(n),
                   np.zeros((n_interfaces, n)), sl)

    # zeta group (mpermH / mpermV) — seeds flow through zetaH/zetaV only
    if zeta_params:
        jzH, jzV, sl = _stacked_zeta_seeds(zeta_params, etaH, freq)
        n = jzH.shape[2]
        _add_block(_zero_eta(n), _zero_eta(n), jzH, jzV,
                   np.zeros((n_interfaces, n)), sl)

    # depth group
    if depth_params:
        jdlo, sl = _stacked_depth_seeds(depth_params, n_interfaces)
        n = jdlo.shape[1]
        _add_block(_zero_eta(n), _zero_eta(n), _zero_eta(n), _zero_eta(n),
                   jdlo, sl)

    # src_z column (zero eta/zeta/depth seeds; carried via indicator)
    if has_src_z:
        if mrec and not msrc:
            raise NotImplementedError(
                "Jacobian w.r.t. 'src_z' is not yet implemented for ME mode "
                "(mrec=True, msrc=False).  Use ab values with electric receivers.")
        src_z_col_idx = col
        _add_block(_zero_eta(1), _zero_eta(1), _zero_eta(1), _zero_eta(1),
                   np.zeros((n_interfaces, 1)), {'src_z': slice(0, 1)})
    else:
        src_z_col_idx = -1

    # rec_z column
    if has_rec_z:
        if mrec and not msrc:
            raise NotImplementedError(
                "Jacobian w.r.t. 'rec_z' is not yet implemented for ME mode "
                "(mrec=True, msrc=False).  Use ab values with electric receivers.")
        rec_z_col_idx = col
        _add_block(_zero_eta(1), _zero_eta(1), _zero_eta(1), _zero_eta(1),
                   np.zeros((n_interfaces, 1)), {'rec_z': slice(0, 1)})
    else:
        rec_z_col_idx = -1

    n_params = col

    if n_params > 0:
        jac_etaH_in  = np.concatenate(bl_eH,  axis=2)
        jac_etaV_in  = np.concatenate(bl_eV,  axis=2)
        jac_zetaH_in = np.concatenate(bl_zH,  axis=2)
        jac_zetaV_in = np.concatenate(bl_zV,  axis=2)
        jac_dlo_in   = np.concatenate(bl_dlo, axis=1)
    else:  # off-only (or no kernel params)
        jac_etaH_in  = _zero_eta(0)
        jac_etaV_in  = _zero_eta(0)
        jac_zetaH_in = _zero_eta(0)
        jac_zetaV_in = _zero_eta(0)
        jac_dlo_in   = np.zeros((n_interfaces, 0))

    # Indicator vectors: 1.0 at the relevant column, 0.0 elsewhere
    jac_src_z_indicator = np.zeros(n_params)
    if has_src_z:
        jac_src_z_indicator[src_z_col_idx] = 1.0
    jac_rec_z_indicator = np.zeros(n_params)
    if has_rec_z:
        jac_rec_z_indicator[rec_z_col_idx] = 1.0

    # Shared keyword args for transform.dlf calls below
    _dlf_kw = dict(dlf=htarg_jac['dlf'], pts_per_dec=0,
                   ang_fact=ang_fact, ab=ab_calc, int_pts=None)

    def _run_wavenumber(eH, eV, zH, zV, lmbd, jH, jV, jzH, jzV):
        """Single kernel.wavenumber call; returns (jPJ0, jPJ1, jPJ0b)."""
        _, _, _, jPJ0, jPJ1, jPJ0b = kernel.wavenumber(
            zsrc, zrec, lsrc, lrec, depth, eH, eV, zH, zV,
            lmbd, ab_calc, xdirect, msrc, mrec, jH, jV,
            jac_dlo_in, jac_src_z_indicator, src_z_col_idx,
            jac_rec_z_indicator, rec_z_col_idx, jzH, jzV)
        return jPJ0, jPJ1, jPJ0b

    def _dlf_cols(jPJ0, jPJ1, jPJ0b, lmbd, off_arr, af, dest):
        """DLF-transform each Jacobian column into dest[:, :, :]."""
        kw = dict(_dlf_kw); kw['ang_fact'] = af; kw['int_pts'] = None
        for k in range(n_params):
            jac_PJ_k = (
                jPJ0[:, :, :, k]  if jPJ0  is not None else None,
                jPJ1[:, :, :, k]  if jPJ1  is not None else None,
                jPJ0b[:, :, :, k] if jPJ0b is not None else None,
            )
            dest[:, :, k] = transform.dlf(
                jac_PJ_k, lmbd, off_arr,
                htarg_jac['dlf'], 0, ang_fact=af, ab=ab_calc, int_pts=None)

    jac_EM = np.zeros((freq.size, off.size, n_params), dtype=etaH.dtype)

    if n_params > 0:   # kernel-flowing params (eta/depth/src_z/rec_z)
        if not (loop_freq or loop_off):
            # --- Default: single vectorised pass over all freqs and offsets ---
            jPJ0, jPJ1, jPJ0b = _run_wavenumber(
                etaH, etaV, zetaH, zetaV, lambd, jac_etaH_in, jac_etaV_in,
                jac_zetaH_in, jac_zetaV_in)
            _dlf_cols(jPJ0, jPJ1, jPJ0b, lambd, off, ang_fact, jac_EM)

        elif loop_freq:
            # --- Memory-saving: one frequency at a time ---
            for i_f in range(freq.size):
                jPJ0_f, jPJ1_f, jPJ0b_f = _run_wavenumber(
                    etaH [None, i_f, :], etaV [None, i_f, :],
                    zetaH[None, i_f, :], zetaV[None, i_f, :],
                    lambd,
                    jac_etaH_in[None, i_f, :, :], jac_etaV_in[None, i_f, :, :],
                    jac_zetaH_in[None, i_f, :, :], jac_zetaV_in[None, i_f, :, :])
                _dlf_cols(jPJ0_f, jPJ1_f, jPJ0b_f, lambd, off, ang_fact,
                          jac_EM[i_f:i_f+1, :, :])

        else:   # loop_off
            # --- Memory-saving: one offset at a time ---
            for ii in range(off.size):
                lmbd_ii = lambd[ii:ii+1, :]   # shape (1, nlambda)
                af_ii   = ang_fact[ii:ii+1]   # shape (1,) per offset
                jPJ0_ii, jPJ1_ii, jPJ0b_ii = _run_wavenumber(
                    etaH, etaV, zetaH, zetaV,
                    lmbd_ii,
                    jac_etaH_in, jac_etaV_in, jac_zetaH_in, jac_zetaV_in)
                _dlf_cols(jPJ0_ii, jPJ1_ii, jPJ0b_ii,
                          lmbd_ii, off[ii:ii+1], af_ii,
                          jac_EM[:, ii:ii+1, :])

    # --- Offset ('off') column: post-process the PRIMAL wavenumber arrays ---
    # The offset derivative does not flow through the kernel Jacobian; it is the
    # Bessel-derivative of the Hankel transform applied to the primal PJ arrays.
    if has_off:
        PJ0_p, PJ1_p, PJ0b_p = kernel.wavenumber(
            zsrc, zrec, lsrc, lrec, depth, etaH, etaV, zetaH, zetaV,
            lambd, ab_calc, xdirect, msrc, mrec)
        off_col = _offset_derivative(
            PJ0_p, PJ1_p, PJ0b_p, lambd, off, htarg_jac['dlf'], ang_fact,
            ab_calc)
        jac_EM = np.concatenate([jac_EM, off_col[:, :, None]], axis=2)
        all_slices['off'] = slice(n_params, n_params + 1)
        n_params += 1

    # Fourier (f→t) transform if time-domain — chain rule: J_t = FT[J_f]
    if signal is not None:
        jac_EM_time = np.zeros((time.size, off.size, n_params))
        for k in range(n_params):
            jac_EM_time[:, :, k], _ = tem(
                jac_EM[:, :, k], off, freq, time, signal, ft, ftarg)
        jac_EM = jac_EM_time

    # Reshape Jacobian to (ntime_or_nfreq, nrec, nsrc, n_params), drop nsrc when 1.
    # The -1 adapts to time.size or freq.size automatically.
    jac_EM = jac_EM.reshape((-1, nrec, nsrc, n_params), order='F')
    if nsrc == 1:
        jac_EM = jac_EM[:, :, 0, :]  # (nfreq, nrec, n_params)

    # Slice into per-parameter arrays and return.
    jac_out = {p: jac_EM[..., sl] for p, sl in all_slices.items()}

    if isinstance(jac, str):
        return EM_out, jac_out[jac]
    return EM_out, jac_out

def analytical(src, rec, res, freqtime, solution='fs', signal=None, ab=11,
               aniso=None, epermH=None, epermV=None, mpermH=None, mpermV=None,
               **kwargs):
    r"""Return analytical full- or half-space solution.

    Calculate the electromagnetic frequency- or time-domain field due to
    infinitesimal small electric or magnetic dipole source(s), measured by
    infinitesimal small electric or magnetic dipole receiver(s); sources and
    receivers are directed along the principal directions x, y, or z, and all
    sources are at the same depth, as well as all receivers are at the same
    depth.

    In the case of a halfspace the air-interface is located at z = 0 m, and
    both sources and receiver must be either at the interface or within the
    subsurface, not in the air (this is NOT checked by the code).

    You can call the functions :func:`empygrad.kernel.fullspace` and
    :func:`empygrad.kernel.halfspace` in :mod:`empygrad.kernel` directly. This
    interface is just to provide a consistent interface with the same input
    parameters as for instance for :func:`dipole`.

    This function yields the same result if ``solution='fs'`` as
    :func:`dipole`, if the model is a fullspace.

    Included are:

    - Full fullspace solution (``solution='fs'``) for ee-, me-, em-, mm-fields,
      only frequency domain, [HuTS15]_.
    - Diffusive fullspace solution (``solution='dfs'``) for ee-fields,
      [SlHM10]_.
    - Diffusive halfspace solution (``solution='dhs'``) for ee-fields,
      [SlHM10]_.
    - Diffusive direct- and reflected field and airwave (``solution='dsplit'``)
      for ee-fields, [SlHM10]_.
    - Diffusive direct- and reflected field and airwave (``solution='dtetm'``)
      for ee-fields, split into TE and TM mode [SlHM10]_.

    Parameters
    ----------
    src, rec : list of floats or arrays
        Source and receiver coordinates [x, y, z] (m):

        For `N` sources or receivers, the x- and y-coordinates must be of size
        `N` or 1 (in the latter case it will be expanded to `N`); z is always a
        single value.

        In the case of the diffusive halfspace, ``z`` is assumed to be at the
        interface or below.

    res : float
        Horizontal resistivity rho_h (Ohm.m).

        Alternatively, res can be a dictionary. See the main manual of empygrad
        too see how to exploit this hook to re-calculate etaH, etaV, zetaH, and
        zetaV, which can be used to, for instance, use the Cole-Cole model for
        IP.

    freqtime : array_like
        Frequencies f (Hz) if ``signal==None``, else times t (s); (f, t > 0).

    solution : str, default: 'fs'
      Defines which solution is returned:

      - 'fs' : Full fullspace solution (ee-, me-, em-, mm-fields); f-domain.
      - 'dfs' : Diffusive fullspace solution (ee-fields only).
      - 'dhs' : Diffusive halfspace solution (ee-fields only).
      - 'dsplit' : Diffusive direct- and reflected field and airwave (ee-fields
        only).
      - 'dtetm' : as dsplit, but direct fielt TE, TM; reflected field TE, TM,
        and airwave (ee-fields only).

    signal : {None, 0, 1, -1}, default: None
        Source signal:

        - None: Frequency-domain response
        - -1 : Switch-off time-domain response
        - 0 : Impulse time-domain response
        - +1 : Switch-on time-domain response

    ab : int, default: 11
        Source-receiver configuration.

        +---------------+-------+------+------+------+------+------+------+
        |                       | electric  source   | magnetic source    |
        +===============+=======+======+======+======+======+======+======+
        |                       | **x**| **y**| **z**| **x**| **y**| **z**|
        +---------------+-------+------+------+------+------+------+------+
        |               | **x** |  11  |  12  |  13  |  14  |  15  |  16  |
        + **electric**  +-------+------+------+------+------+------+------+
        |               | **y** |  21  |  22  |  23  |  24  |  25  |  26  |
        + **receiver**  +-------+------+------+------+------+------+------+
        |               | **z** |  31  |  32  |  33  |  34  |  35  |  36  |
        +---------------+-------+------+------+------+------+------+------+
        |               | **x** |  41  |  42  |  43  |  44  |  45  |  46  |
        + **magnetic**  +-------+------+------+------+------+------+------+
        |               | **y** |  51  |  52  |  53  |  54  |  55  |  56  |
        + **receiver**  +-------+------+------+------+------+------+------+
        |               | **z** |  61  |  62  |  63  |  64  |  65  |  66  |
        +---------------+-------+------+------+------+------+------+------+

    aniso : float, default: 1.0
        Anisotropy lambda = sqrt(rho_v/rho_h) (-).

    epermH, epermV : float, default: 1.0
        Relative horizontal/vertical electric permittivity
        epsilon_h/epsilon_v (-). If epermH is provided but not epermV,
        isotropic behaviour is assumed.
        These parameters are ignored for the diffusive solution.

    mpermH, mpermV : float, default: 1.0
        Relative horizontal/vertical magnetic permeability mu_h/mu_v (-);
        #mpermH = #mpermV = #res. If mpermH is provided but not mpermV,
        isotropic behaviour is assumed.
        These parameters are ignored for the diffusive solution.

    verb : {0, 1, 2, 3, 4}, default: 2
        Level of verbosity:

        - 0: Print nothing.
        - 1: Print warnings.
        - 2: Print additional runtime
        - 3: Print additional start/stop, condensed parameter information.
        - 4: Print additional full parameter information

    squeeze : bool, default: True
        If True, the output is squeezed. If False, the output will always be of
        ``ndim=3``, (nfreqtime, nrec, nsrc).


    Returns
    -------
    EM : EMArray, (nfreqtime, nrec, nsrc)
        Frequency- or time-domain EM field (depending on ``signal``):

        - If rec is electric, returns E [V/m].
        - If rec is magnetic, returns H [A/m].

        EMArray is a subclassed ndarray with ``.pha`` and ``.amp`` attributes
        (only relevant for frequency-domain data).

        The shape of EM is (nfreqtime, nrec, nsrc). However, single dimensions
        are removed.

        If ``solution='dsplit'``, three ndarrays are returned: direct, reflect,
        air.

        If ``solution='dtetm'``, five ndarrays are returned: direct_TE,
        direct_TM, reflect_TE, reflect_TM, air.


    Examples
    --------

    .. ipython::

       In [1]: import empygrad
          ...: import numpy as np
          ...: src = [0, 0, 0]
          ...: rec = [np.arange(1, 11)*500, np.zeros(10), 200]
          ...: res = 50
          ...: EMfield = empygrad.analytical(src, rec, res, freqtime=1, verb=0)
          ...: EMfield[0]
       Out[1]: (4.030914049602561e-08-9.691638183648923e-10j)

    """
    # Get kwargs with defaults.
    verb, squeeze = get_kwargs(['verb', 'squeeze'], [2, True], kwargs)

    # === 1.  LET'S START ============
    t0 = printstartfinish(verb)

    # === 2.  CHECK INPUT ============

    # Check times or frequencies
    if signal is not None:
        freqtime, _ = check_time_only(freqtime, signal, verb, True)

    # Check layer parameters
    model = check_model([], res, aniso, epermH, epermV, mpermH, mpermV, True,
                        verb)
    depth, res, aniso, epermH, epermV, mpermH, mpermV, _ = model

    # Check frequency => get etaH, etaV, zetaH, and zetaV
    frequency = check_frequency(freqtime, res, aniso, epermH, epermV, mpermH,
                                mpermV, verb)
    freq, etaH, etaV, zetaH, zetaV = frequency

    # Update etaH/etaV and zetaH/zetaV according to user-provided model
    if isinstance(res, dict) and 'func_eta' in res:
        etaH, etaV = res['func_eta'](res, locals())
    if isinstance(res, dict) and 'func_zeta' in res:
        zetaH, zetaV = res['func_zeta'](res, locals())

    # Check src-rec configuration
    # => Get flags if src or rec or both are magnetic (msrc, mrec)
    ab_calc, msrc, mrec = check_ab(ab, verb)

    # Check src and rec
    src, nsrc = check_dipole(src, 'src', verb)
    rec, nrec = check_dipole(rec, 'rec', verb)

    # Get offsets and angles (off, angle)
    off, angle = get_off_ang(src, rec, nsrc, nrec, verb)

    # Get layer number in which src and rec reside (lsrc/lrec)
    _, zsrc = get_layer_nr(src, depth)
    _, zrec = get_layer_nr(rec, depth)

    # Check possibilities
    check_solution(solution, signal, ab, msrc, mrec)

    # === 3. EM-FIELD CALCULATION ============

    if solution[0] == 'd':
        # To make it work with Laplace domain calculations.
        if signal is None:
            if np.any(freqtime > 0):
                freqtime = 2j*np.pi*freq
            else:
                freqtime = freq
        EM = kernel.halfspace(off, angle, zsrc, zrec, etaH, etaV,
                              freqtime[:, None], ab_calc, signal, solution)
    else:
        if ab_calc not in [36, ]:
            EM = kernel.fullspace(off, angle, zsrc, zrec, etaH, etaV, zetaH,
                                  zetaV, ab_calc, msrc, mrec)
        else:
            # If <ab> = 36 (or 63), field is zero
            # In `bipole` and in `dipole`, this is taken care of in `fem`. Here
            # we have to take care of it separately
            EM = np.zeros((freq.size*nrec*nsrc), dtype=etaH.dtype)

    # Reshape for number of sources
    if solution[1:] == 'split':
        EM = (EM[0].reshape((-1, nrec, nsrc), order='F'),
              EM[1].reshape((-1, nrec, nsrc), order='F'),
              EM[2].reshape((-1, nrec, nsrc), order='F'))
    elif solution[1:] == 'tetm':
        EM = (EM[0].reshape((-1, nrec, nsrc), order='F'),
              EM[1].reshape((-1, nrec, nsrc), order='F'),
              EM[2].reshape((-1, nrec, nsrc), order='F'),
              EM[3].reshape((-1, nrec, nsrc), order='F'),
              EM[4].reshape((-1, nrec, nsrc), order='F'))
    else:
        EM = EM.reshape((-1, nrec, nsrc), order='F')
    if squeeze:
        EM = np.squeeze(EM)

    # === 4.  FINISHED ============
    printstartfinish(verb, t0)

    return EMArray(EM)


def gpr(src, rec, depth, res, freqtime, cf, gain=None, ab=11, aniso=None,
        epermH=None, epermV=None, mpermH=None, mpermV=None, **kwargs):
    r"""Return Ground-Penetrating Radar signal.

    THIS FUNCTION IS EXPERIMENTAL, USE WITH CAUTION.

    It is rather an example how you can calculate GPR responses; however, DO
    NOT RELY ON IT! It works only well with QUAD or QWE (``quad``, ``qwe``) for
    the Hankel transform, and with FFT (``fft``) for the Fourier transform.

    It calls internally :func:`dipole` for the frequency-domain calculation. It
    subsequently convolves the response with a Ricker wavelet with central
    frequency ``cf``. If signal!=None, it carries out the Fourier transform and
    applies a gain to the response.


    Parameters
    ----------
    src, rec, freqtime : survey parameters
        See docstring of :func:`dipole` for a description.

    depth, res, aniso, epermH, epermV, mpermH, mpermV : model parameters
        See docstring of :func:`dipole` for a description.

    cf : float
        Centre frequency of GPR-signal, in Hz. Sensible values are between
        10 MHz and 3000 MHz.

    gain : float
        Power of gain function. If None, no gain is applied. Only used if
        signal!=None.

    ht, htarg, ft, ftarg, xdirect, loop : settings, optinal
        See docstring of :func:`bipole` for a description.


    Returns
    -------
    EM : ndarray
        GPR response

    """
    # Get kwargs with defaults.
    out = get_kwargs(['verb', 'ht', 'htarg', 'ft', 'ftarg', 'xdirect', 'loop'],
                     [2, 'quad', {}, 'fft', {}, False, None], kwargs)
    verb, ht, htarg, ft, ftarg, xdirect, loop = out

    if verb > 2:
        print("   GPR             :  EXPERIMENTAL, USE WITH CAUTION")
        print(f"     > centre freq :  {cf}")
        print(f"     > gain        :  {gain}")

    # === 1.  CHECK TIME ============

    # Check times and Fourier Transform arguments, get required frequencies
    time, freq, ft, ftarg, _ = check_time(freqtime, 0, ft, ftarg, verb, True)

    # === 2. CALL DIPOLE ============

    EM = dipole(src=src, rec=rec, depth=depth, res=res, freqtime=freq, ab=ab,
                aniso=aniso, epermH=epermH, epermV=epermV, mpermH=mpermH,
                mpermV=mpermV, xdirect=xdirect, ht=ht, htarg=htarg, ft=ft,
                ftarg=ftarg, loop=loop, verb=verb)

    # === 3. GPR STUFF

    # Get required parameters
    src, nsrc = check_dipole(src, 'src', 0)
    rec, nrec = check_dipole(rec, 'rec', 0)
    off, _ = get_off_ang(src, rec, nsrc, nrec, 0)

    # Reshape output from dipole
    EM = EM.reshape((-1, nrec*nsrc), order='F')

    # Multiply with ricker wavelet
    cfc = -(np.r_[0, freq[:-1]]/cf)**2
    fwave = cfc*np.exp(cfc)
    EM *= fwave[:, None]

    # Do f->t transform
    EM, conv = tem(EM, off, freq, time, 0, ft, ftarg)

    # In case of QWE/QUAD, print Warning if not converged
    conv_warning(conv, ftarg, 'Fourier', verb)

    # Apply gain; make pure real
    EM *= (1 + np.abs((time*10**9)**gain))[:, None]
    EM = EM.real

    # Reshape for number of sources
    EM = np.squeeze(EM.reshape((-1, nrec, nsrc), order='F'))

    return EM


def dipole_k(src, rec, depth, res, freq, wavenumber, ab=11, aniso=None,
             epermH=None, epermV=None, mpermH=None, mpermV=None, **kwargs):
    r"""Return electromagnetic wavenumber-domain field.

    Calculate the electromagnetic wavenumber-domain field due to infinitesimal
    small electric or magnetic dipole source(s), measured by infinitesimal
    small electric or magnetic dipole receiver(s); sources and receivers are
    directed along the principal directions x, y, or z, and all sources are at
    the same depth, as well as all receivers are at the same depth.


    See Also
    --------
    :func:`dipole` : EM fields due to infinitesimal small EM dipoles.
    :func:`bipole` : EM fields due to arbitrary rotated, finite length EM
                     dipoles.
    :func:`loop` : EM fields due to a magnetic source loop.


    Parameters
    ----------
    src, rec : list of floats or arrays
        Source and receiver coordinates [x, y, z] (m):

        - For `N` sources or receivers, the x- and y-coordinates must be of
          size `N` or 1 (in the latter case it will be expanded to `N`); z is
          always a single value.
        - The x- and y-coordinates only matter for the angle-dependent factor.

        Sources or receivers placed on a layer interface are considered in the
        upper layer.

    depth : list
        Absolute layer interfaces z (m); #depth = #res - 1
        (excluding +/- infinity).

    res : array_like
        Horizontal resistivities rho_h (Ohm.m); #res = #depth + 1.

    freq : array_like
        Frequencies f (Hz), used to calculate etaH/V and zetaH/V.

    wavenumber : array
        Wavenumbers lambda (1/m)

    ab : int, default: 11
        Source-receiver configuration.

        +---------------+-------+------+------+------+------+------+------+
        |                       | electric  source   | magnetic source    |
        +===============+=======+======+======+======+======+======+======+
        |                       | **x**| **y**| **z**| **x**| **y**| **z**|
        +---------------+-------+------+------+------+------+------+------+
        |               | **x** |  11  |  12  |  13  |  14  |  15  |  16  |
        + **electric**  +-------+------+------+------+------+------+------+
        |               | **y** |  21  |  22  |  23  |  24  |  25  |  26  |
        + **receiver**  +-------+------+------+------+------+------+------+
        |               | **z** |  31  |  32  |  33  |  34  |  35  |  36  |
        +---------------+-------+------+------+------+------+------+------+
        |               | **x** |  41  |  42  |  43  |  44  |  45  |  46  |
        + **magnetic**  +-------+------+------+------+------+------+------+
        |               | **y** |  51  |  52  |  53  |  54  |  55  |  56  |
        + **receiver**  +-------+------+------+------+------+------+------+
        |               | **z** |  61  |  62  |  63  |  64  |  65  |  66  |
        +---------------+-------+------+------+------+------+------+------+

    aniso : array_like, default: ones
        Anisotropies lambda = sqrt(rho_v/rho_h) (-); #aniso = #res.

    epermH, epermV : array_like, default: ones
        Relative horizontal/vertical electric permittivities
        epsilon_h/epsilon_v (-); #epermH = #epermV = #res. If epermH is
        provided but not epermV, isotropic behaviour is assumed.

    mpermH, mpermV : array_like, default: ones
        Relative horizontal/vertical magnetic permeabilities mu_h/mu_v (-);
        #mpermH = #mpermV = #res. If mpermH is provided but not mpermV,
        isotropic behaviour is assumed.

    verb : {0, 1, 2, 3, 4}, default: 2
        Level of verbosity:

        - 0: Print nothing.
        - 1: Print warnings.
        - 2: Print additional runtime and kernel calls
        - 3: Print additional start/stop, condensed parameter information.
        - 4: Print additional full parameter information


    Returns
    -------
    PJ0, PJ1 : array
        Wavenumber-domain EM responses:

        - PJ0: Wavenumber-domain solution for the kernel with a Bessel function
          of the first kind of order zero.
        - PJ1: Wavenumber-domain solution for the kernel with a Bessel function
          of the first kind of order one.


    Examples
    --------

    .. ipython::

       In [1]: import empygrad
          ...: import numpy as np
          ...: src = [0, 0, 100]
          ...: rec = [5000, 0, 200]
          ...: depth = [0, 300, 1000, 1050]
          ...: res = [1e20, .3, 1, 50, 1]
          ...: freq = 1
          ...: wavenr = np.logspace(-3.7, -3.6, 10)
          ...: PJ0, PJ1 = empygrad.dipole_k(
          ...:         src, rec, depth, res, freq, wavenr, verb=0)
          ...: PJ0[0]
       Out[1]: (-2.5768974970445326e-08-2.0489943182087426e-09j)

       In [2]: PJ1[0]
       Out[2]: (1.9050482781619523e-10-6.842938067042929e-10j)

    """
    # Get kwargs with defaults.
    verb = get_kwargs(['verb', ], [2, ], kwargs)[0]

    # === 1.  LET'S START ============
    t0 = printstartfinish(verb)

    # === 2.  CHECK INPUT ============

    # Check layer parameters (isfullspace not required)
    modl = check_model(depth, res, aniso, epermH, epermV, mpermH, mpermV,
                       False, verb)
    depth, res, aniso, epermH, epermV, mpermH, mpermV, _ = modl

    # Check frequency => get etaH, etaV, zetaH, and zetaV
    f = check_frequency(freq, res, aniso, epermH, epermV, mpermH, mpermV, verb)
    freq, etaH, etaV, zetaH, zetaV = f

    # Check src-rec configuration
    # => Get flags if src or rec or both are magnetic (msrc, mrec)
    ab_calc, msrc, mrec = check_ab(ab, verb)

    # Check src and rec
    src, nsrc = check_dipole(src, 'src', verb)
    rec, nrec = check_dipole(rec, 'rec', verb)

    # Get angle-dependent factor
    off, angle = get_off_ang(src, rec, nsrc, nrec, verb)
    ang_fact = kernel.angle_factor(angle, ab, msrc, mrec)

    # Get layer number in which src and rec reside (lsrc/lrec)
    lsrc, zsrc = get_layer_nr(src, depth)
    lrec, zrec = get_layer_nr(rec, depth)

    # === 3. EM-FIELD CALCULATION ============

    # Pre-allocate
    if off.size == 1 and np.ndim(wavenumber) == 2:
        PJ0 = np.zeros((freq.size, wavenumber.shape[0], wavenumber.shape[1]),
                       dtype=etaH.dtype)
        PJ1 = np.zeros((freq.size, wavenumber.shape[0], wavenumber.shape[1]),
                       dtype=etaH.dtype)
    else:
        PJ0 = np.zeros((freq.size, off.size, wavenumber.size),
                       dtype=etaH.dtype)
        PJ1 = np.zeros((freq.size, off.size, wavenumber.size),
                       dtype=etaH.dtype)

    # If <ab> = 36 (or 63), field is zero
    # In `bipole` and in `dipole`, this is taken care of in `fem`. Here we
    # have to take care of it separately
    if ab_calc not in [36, ]:

        # Calculate wavenumber response
        J0, J1, J0b = kernel.wavenumber(zsrc, zrec, lsrc, lrec, depth, etaH,
                                        etaV, zetaH, zetaV,
                                        np.atleast_2d(wavenumber), ab_calc,
                                        False, msrc, mrec)

        # Collect output
        if J1 is not None:
            PJ1 += ang_fact[:, np.newaxis]*J1
            if ab in [11, 12, 21, 22, 14, 24, 15, 25]:  # Because of J2
                # J2(kr) = 2/(kr)*J1(kr) - J0(kr)
                PJ1 /= off[:, None]
        if J0 is not None:
            PJ0 += J0
        if J0b is not None:
            PJ0 += ang_fact[:, np.newaxis]*J0b

    # === 4.  FINISHED ============
    printstartfinish(verb, t0, 1)

    return np.squeeze(PJ0), np.squeeze(PJ1)


def ip_and_q(**kwargs):
    """Return In-Phase and Quadrature components for provided model and system.

    This wrapper calls :func:`dipole` two times:

    - 1st: with ``xdirect=None`` for the secondary field Hs.
    - 2nd: with ``xdirect=True``, and only the first value of all model
      parameters and an empty ``depth``-parameter for the primary field Hp.
      For the primary field, the co-planar field of the source configuration is
      used.

    It then returns the real (in-phase) and imaginary (quadrature) components
    of the ratio Hs/Hp, scaled by ``scale``.

    This function takes the same input parameters as :func:``dipole``; see the
    documentation of dipole for the descriptions. In addition, it takes a
    ``scale`` parameter.

    This function is only implemented for frequency-domain data of magnetic
    sources and receivers.

    .. note::

        This function is experimental. Please let us know if you encounter any
        issues when using this function!

        Also note that for the primary field computation, the co-planar field
        of the source direction is used. Hence:

        - Hp for ab=44 is used for ab in [44, 54, 64],
        - Hp for ab=55 is used for ab in [45, 55, 65],
        - Hp for ab=66 is used for ab in [46, 56, 66].


    Parameters
    ----------
    All parameters : See :func:`dipole`.
      - Restrictions compared to  :func:`dipole`:

        - ``ab`` has to be one of [44, 45, 46, 54, 55, 56, 64, 65, 66]
          (magnetic source and receiver).
        - ``xdirect`` is ignored; it is first set to ``None`` for Hs, and then
          to ``True`` for Hp.
        - ``signal`` has to be ``None`` (frequency domain); ``ft`` and
          ``ftarg`` have hence no effect.

    scale : float, default: 1e3 (ppt)
        Multiplication factor. E.g., 1e3 for ppt, 1e6 for ppm.


    Returns
    -------

    IP, Q : ndarrays
        In-phase and quadrature values.

    """

    # Ensure source and receiver are magnetic.
    if int(kwargs.get('ab', 11)) not in [44, 45, 46, 54, 55, 56, 64, 65, 66]:
        raise ValueError("Only implemented for magnetic sources/receivers.")

    # Ensure signal is None.
    if kwargs.get('signal', None) is not None:
        raise ValueError("Only implemented for frequency domain.")

    # Warning that it has not been thoroughly tested.
    verb = kwargs.get('verb', 2)
    if verb > 0 and not np.allclose(kwargs['src'][2], kwargs['rec'][2]):
        print("* WARNING :: This function is experimental. Please let us know "
              "if you encounter any issues when using this function!")

    # Get or set scale
    scale = kwargs.pop('scale', 1e3)

    # Secondary magnetic field (xdirect=None means no direct field)
    Hs = dipole(**{**kwargs, 'xdirect': None})

    # Primary magnetic field
    new = copy.deepcopy(kwargs)

    # For the primary field, use the co-planar field of source configuration.
    if new['ab'] in [44, 54, 64]:
        new['ab'] = 44
    elif new['ab'] in [45, 55, 65]:
        new['ab'] = 55
    elif new['ab'] in [46, 56, 66]:
        new['ab'] = 66

    # Take only the first value of each parameter, and set depth to empty.
    new['depth'] = []
    for k in ['res', 'aniso', 'epermH', 'epermV', 'mpermH', 'mpermV']:
        if k in kwargs.keys():
            new[k] = np.atleast_1d(kwargs[k])[0]

    # Primary magnetic field (a fullspace of air, hence ONLY the direct field)
    Hp = dipole(**{**new, 'xdirect': True})

    # Take the ratio, multiply by scale
    H = scale * Hs / Hp

    # Return In-phase and Quadrature
    return H.real, H.imag


# Core modelling routines

def fem(ab, off, angle, zsrc, zrec, lsrc, lrec, depth, freq, etaH, etaV, zetaH,
        zetaV, xdirect, isfullspace, ht, htarg, msrc, mrec, loop_freq,
        loop_off, conv=True):
    r"""Return electromagnetic frequency-domain response.

    This function is called from one of the modelling routines
    :mod:`empygrad.model`. Consult those for more details regarding the input
    and output parameters.

    This function can be used directly if you are sure the provided input is in
    the correct format. This is useful for inversion routines and similar, as
    it can speed-up the calculation by omitting input-checks.

    """
    # Preallocate array
    fEM = np.zeros((freq.size, off.size), dtype=etaH.dtype)

    # Initialize kernel count
    # (how many times the wavenumber-domain kernel was calld)
    kcount = 0

    # If <ab> = 36 (or 63), fEM-field is zero
    if ab in [36, ]:
        return fEM, kcount, conv

    # Get full-space-solution if xdirect=True and model is a full-space or
    # if src and rec are in the same layer.
    if xdirect and (isfullspace or lsrc == lrec):
        fEM += kernel.fullspace(off, angle, zsrc, zrec, etaH[:, lrec],
                                etaV[:, lrec], zetaH[:, lrec], zetaV[:, lrec],
                                ab, msrc, mrec)

    # If `xdirect = None` we set it here to True, so it is NOT calculated in
    # the wavenumber domain. (Only reflected fields are returned.)
    if xdirect is None:
        xdir = True
    else:
        xdir = xdirect

    # If not full-space with xdirect calculate fEM-field
    if not isfullspace*xdir:

        # Get angle dependent factors
        ang_fact = kernel.angle_factor(angle, ab, msrc, mrec)

        calc = getattr(transform, 'hankel_'+ht)
        if loop_freq:

            for i in range(freq.size):
                out = calc(zsrc, zrec, lsrc, lrec, off, ang_fact, depth, ab,
                           etaH[None, i, :], etaV[None, i, :],
                           zetaH[None, i, :], zetaV[None, i, :], xdir,
                           htarg, msrc, mrec)
                fEM[None, i, :] += out[0]
                kcount += out[1]
                conv *= out[2]

        elif loop_off:
            for i in range(off.size):

                out = calc(zsrc, zrec, lsrc, lrec, off[None, i],
                           ang_fact[None, i], depth, ab, etaH, etaV, zetaH,
                           zetaV, xdir, htarg, msrc, mrec)
                fEM[:, None, i] += out[0]
                kcount += out[1]
                conv *= out[2]
        else:
            out = calc(zsrc, zrec, lsrc, lrec, off, ang_fact, depth, ab, etaH,
                       etaV, zetaH, zetaV, xdir, htarg, msrc, mrec)
            fEM += out[0]
            kcount += out[1]
            conv *= out[2]

    return fEM, kcount, conv


def tem(fEM, off, freq, time, signal, ft, ftarg, conv=True):
    r"""Return time-domain response of the frequency-domain response fEM.

    This function is called from one of the modelling routines
    :mod:`empygrad.model`. Consult those for more details regarding the input
    and output parameters.

    This function can be used directly if you are sure the provided input is in
    the correct format. This is useful for inversion routines and similar, as
    it can speed-up the calculation by omitting input-checks.

    """
    # Check if standard signal or arbitrary waveform
    if isinstance(signal, dict):
        apply_waveform = signal['apply_waveform']
        signal = signal['signal']
    else:
        apply_waveform = False

    # 1. Scale frequencies if switch-on/off response
    # Step function for causal times is like a unit fct, therefore an impulse
    # in frequency domain
    if signal in [-1, 1]:
        # Divide by signal/(2j*pi*f) to obtain step response
        fact = signal/(2j*np.pi*freq).ravel()
    else:
        fact = 1

    # 2. f->t transform
    calc = getattr(transform, 'fourier_'+ft)
    tEM = np.zeros((time.size, off.size))
    for i in range(off.size):
        out = calc(fEM[:, i]*fact, time, freq, ftarg)
        tEM[:, i] += out[0]
        conv *= out[1]

    tEM *= 2/np.pi  # Scaling from Fourier transform

    # Apply waveform
    if apply_waveform:
        tEM = apply_waveform(tEM)

    return tEM, conv
